export const periodTypesMap = {
    Daily: 'DAILY',
    Weekly: 'WEEKLY',
    WeeklyWednesday: 'WEEKLYWED',
    WeeklyThursday: 'WEEKLYTHU',
    WeeklySaturday: 'WEEKLYSAT',
    WeeklySunday: 'WEEKLYSUN',
    BiWeekly: 'BIWEEKLY',
    Monthly: 'MONTHLY',
    BiMonthly: 'BIMONTHLY',
    Quarterly: 'QUARTERLY',
    QuarterlyNov: 'QUARTERLYNOV',
    SixMonthly: 'SIXMONTHLY',
    SixMonthlyApril: 'SIXMONTHLYAPR',
    SixMonthlyNov: 'SIXMONTHLYNOV',
    Yearly: 'YEARLY',
    FinancialApril: 'FYAPR',
    FinancialJuly: 'FYJUL',
    FinancialOct: 'FYOCT',
    FinancialNov: 'FYNOV',
}
